# This is a Docker Compose file for local development of the Digital Growth Charts documentation.

services:
  mkdocs: # Digital Growth Charts Documentation
    build: .
    environment:
      - ENABLE_PDF_EXPORT=0 # Makes PDF export an option, default disabled for local dev
      - ENABLE_GIT_COMMITTERS=True # Makes git-committers an option, default enabled
    volumes:
      - .:/app
    ports:
      - 8001:8000 # Zensical will be accessible at localhost:8001
    command: sh -c "zensical serve --dev-addr=0.0.0.0:8000"
    restart: always
