site_name: RCPCH Digital Growth Charts API 
site_description: RCPCH Digital Growth Charts API Project Documentation Site
site_author: The Royal College of Paediatrics and Child Health
site_url: https://rcpch.github.io/digital-growth-charts-documentation/

nav:
  - Home: 'index.md'
  - About:
    - 'about/about.md'
    - 'about/overview.md'
    - 'about/support.md'
    - 'about/team.md'
    - 'about/contact.md'
    - 'about/acknowledgements.md'
  - Products:
    - 'products/products-overview.md'
    - 'products/api-server.md'
    - 'products/react-client.md'
    - 'products/react-component.md'
    - 'products/react-native.md'
    - 'products/command-line-client.md'
    - 'products/python-library.md'
    - 'products/google-sheets-plugin.md'
    - 'products/flask(deprecated).md'
    - 'products/pricing.md'
  - Clinician: 
    - 'clinician/how-the-api-works.md'
    - 'clinician/chart-information-families.md'
    - 'clinician/chart-information-health-staff.md'
    - 'clinician/date-age-calculations.md'
    - 'clinician/growth-references.md'
    - 'clinician/faqs-for-clinicians.md'
  - Integrator:
    - 'integrator/getting-started.md'
    - 'integrator/api-keys.md'
    - 'integrator/making-api-calls.md'
    - 'integrator/api-reference.md'
    - 'integrator/client-specification.md'
    - 'integrator/faqs-for-integrators.md'
    - 'integrator/whos-using-dgc.md'
  - Contribute:
    - 'developer/start-here.md'
    - 'developer/adding-a-new-api-endpoint.md'
    - 'developer/api-docker.md'
    - 'developer/api-python.md'
    - 'developer/contributing.md'
    - 'developer/writing-documentation.md'
    - 'developer/faqs-for-developers.md'
    - RCPCHGrowth Package:
      - 'developer/rcpchgrowth.md'
  - Safety:
    - 'safety/overview.md'
    - Clinical Safety File:
      - 'safety/csmf/clinical-risk-mgmt-system.md'
      - 'safety/csmf/clinical-risk-mgmt-plan.md'
      - 'safety/csmf/hazard-log.md'
      - 'safety/csmf/security.md'
      - 'safety/csmf/third-party-tools-safety-assmt.md'
      - 'safety/csmf/license.md'
    - 'safety/dtac.md'
    - EU Medical Devices:
      - 'safety/eu-mdr/doc-api.md'
      - 'safety/eu-mdr/mdr-technical-docs.md'
    - MHRA:
      - 'safety/mhra.md'
      - 'safety/essential-req.md'
  - Legal:
    - 'legal/disclaimer.md'
    - 'legal/licensing-copyright.md'
    - 'legal/data-protection.md'
    - 'legal/privacy.md'
  - Technical:
    - 'technical/status.md'


theme:
  name: material
  custom_dir: rcpch-theme
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.expand
    # - toc.integrate

  palette:
    # Light mode ONLY - it's gets too hard to keep dark mode working with a number of iframes in play
      scheme: default


  font:
    text: Montserrat
    code: Roboto Mono

  favicon: _assets/_images/dynamic-child-favicon.png
  logo: _assets/_images/logo-desktop.svg

plugins:
  - render_swagger
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

copyright: Copyright &copy; 2021 Royal College of Paediatrics and Child Health (RCPCH)
repo_url: https://github.com/rcpch/digital-growth-charts-documentation
edit_uri: blob/live/docs

extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rcpchtweets
    - icon: fontawesome/brands/github
      link: https://github.com/rcpch
    - icon: fontawesome/brands/discourse
      link: https://openhealthhub.org/c/rcpch-digital-growth-charts
    - icon: material/chat
      link: https://signal.group/#CjQKIAjLf5lS9OZIAI6lsJKWP1LmeJXkUW_fzZH1ryEw3oFEEhBH-4F7WnlyYjKerjfzD6B0

