#!/bin/bash

set -v  # Enable verbose mode
set -e  # Exit on error

# scripts may need to be made executable on some platforms before they can be run
# chmod +x s/linkcheck

# Builds the site in strict mode to validate internal links and anchors.
# Usage:
#   s/linkcheck              # validates internal links and anchors
#   s/linkcheck <args...>    # passes extra args to zensical build

docker compose run --rm \
  zensical \
  zensical build --clean --strict "$@"
