# This Action builds the documentation site in mkdocs, and pushes it to the gh-pages branch, from where it is deployed
# GitHub pages is the BACKUP SITE: https://rcpch.github.io/digital-growth-charts-documentation/
# Azure Static Web Sites is the LIVE site https://growth.rcpch.ac.uk/

name: build-and-deploy-to-gh-pages.yml
on:
  push:
    branches:
      - live
jobs:
  build-and-deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'live'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-render-swagger-plugin
      - run: mkdocs gh-deploy --force # Output files are force-pushed to gh-pages branch
      
  deploy-gh-pages-branch-to-azure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages' # Use the newly-built 'gh-pages' branch not the default 'live' branch
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_GLACIER_063C32703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

