# Uses https://github.com/crazy-max/ghaction-github-labeler
# Manually run the Action in the GitHub UI to add Hazard Log Labels as per the YAML file

name: create-hazard-log-labels

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Labeller
        if: success()
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true # won't delete your existing labels
          dry-run: false
